### ISSUE TITLE
Да се увеличи размера на качваните файлове

### ISSUE THREAD

**Issue by mitio** [governmentbg/opendata#14]
В момента е много малък. Инфраструктурно, има Nginx + Apache, но лимитът в Nginx е вдигнат. Въпреки това, все още дава грешка на ниво upload.

> "Файлът е 55,2 MB, зипнат е 13,4 MB."

Дава следната грешка:

![opendata-file-size-error](https://cloud.githubusercontent.com/assets/129307/7046905/a233c908-de11-11e4-9ce4-e91a1bc9ec6c.jpg)

В datapusher компонента сме [увеличили размера на файловете](https://github.com/governmentbg/ckan-datapusher/commit/3c8e117969b30e1c8257b53481aa6f16e58baa78), но това е отделен проблем.

@Glamdring намери това: https://github.com/ckan/ckan/blob/8e15127f3e5ddda6334d080c198234a33044df76/ckan/lib/uploader.py#L117

**Comment by mitio** [comment]
@Glamdring Това го има и [в нашия fork](https://github.com/governmentbg/ckan/blob/8e15127f3e5ddda6334d080c198234a33044df76/ckan/lib/uploader.py#L117). Трябва да видим къде се вика.

Отделно, виждам, че ckan-storage има опция `ckan.max_resource_size` в `production.ini`, която изглежда да е сложена на 10 (ябълки, круши, мегабайти...) в момента. Ще експериментирам да я 
вдигна.

**Comment by mitio** [comment]
Това е опцията, която трябва да сменим в `production.ini`:

```
ckan.max_resource_size
```

Мери се в MB и по подразбиране е 10 MB. [Ето документация.](http://docs.ckan.org/en/latest/maintaining/configuration.html?highlight=storage#ckan-max-resource-size)

Смених я на 1000 и тествах преди и след – работи. Пушка сме.

**Comment by mitio** [comment]
Добавено е вече и [в инсталационната процедура](https://github.com/governmentbg/ckan-install/commit/53206330e5872a3972af8515d35005cf51151959).

**Comment by antitoxic** [comment]
Тук трябва да се добави промвнливата:
https://github.com/governmentbg/ckan-install/blob/master/debian/init.sh#L137

Ще имам време за това понеделника.
