### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by Glamdring** [governmentbg/opendata#18]
Да сложим Google Analytics, за да следим ползването. GA профилът е хубаво да се направи с някой правителствен акаунт, а не с наш. Ако някой тръгне да го прави, различен от мен, да ми пише, ще дам GA код.

**Comment by Glamdring** [comment]
```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-64544691-1', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by ignisf** [comment]
@Glamdring, помисли какви функционалности на google analytics биха ти липсвали в инструмент за анализ на логовете на уеб сървъра, преди да вкараш код за проследяване.

IMO до голяма степен ползата от шифрирана връзка с портала ще бъде неутрализирана от това, че всеки клиент ще докладва на google точно коя страница е отворил.

**Comment by Glamdring** [comment]
@ignisf аз съм окей и с анализ на логове, ако има уеб интерфейс и дава статистики за период, както и referers. Но не знам какъв.

**Comment by Glamdring** [comment]
Същон search keywords

**Comment by krokodilerian** [comment]
Стандартното е webalizer, ама доколкото знам всички го мразят. Иначе да, анализът на логове е най-приличния вариант, който ми хрумва, въпреки че не хваща толкова много информация.

**Comment by ignisf** [comment]
rattus предлага piwik

**Comment by Glamdring** [comment]
ОК, ами да сложим piwik?

**Comment by Glamdring** [comment]
@ignisf @mitio аз ли да го направя, или имате know-how и ще го направите по-бързо? :)

**Comment by mitio** [comment]
@Glamdring Аз нямам know-how за това, в момента не разполагам и с време, за да го разуча и подкарам.

Аз гласувам да сложим Google Analytics сега и да reevaluate-нем този въпрос пак в близкото бъдеще - примерно, след половин-една година.

Разбирам притесненията от гледна точка на сигурност, изказани по-горе. Бих пробвал това piwik, но съм много скептичен. Честно казано, ползите от информацията, която идва от Google Analytics, леснотата на интеграция и централизираното събиране на информация за мен превишават потенциалния риск, че Google ще знаят, че аз съм посетил държавният сайт Х и че съм цъкал там страницата Y или Z.

Това за мен определено е тема, която си заслужава да се обсъди по-внимателно и ако може добре да се запази privacy-то на хората чрез събиране и анализиране на логовете с някакъв централизиран, in-house инструмент, това би било супер, но за момента бих стартирал с Google Analytics.

**Comment by mitio** [comment]
Допълнително, ако ще се слага Google Analytics, трябва да се напрви в [ckan-bulgarian-theme](https://github.com/governmentbg/ckan-bulgarian-theme), след което да се деплойне само темата (някакви [инструкции за това има тук](https://github.com/governmentbg/ckan-install/blob/master/debian/init.sh)).

И още нещо - имаше един по-нов, anync синтаксис за Google Analytics, с `_gaq.push(...)` и след това един HTTP(S) call. По-добре да ползваме него.

**Comment by Glamdring** [comment]
Искрен прати код, по-добре него да ползваме (тия дни ще гледам да го сложа)

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-65130379-1', 'auto');
  ga('send', 'pageview');
</script>
```

**Comment by mitio** [comment]
Сложили сме Google Analytics в момента.

Затварям това issue и местим дискусията в #20.
