### ISSUE TITLE
Сайтът не работи с www отпред

### ISSUE THREAD

**Issue by mitio** [governmentbg/opendata#19]
Някои хора опитват да отворят адреса на портала слагайки www отпред и това, естествено, не работи.

В този случай, най-дорбе да го направим да работи и просто да препраща към адреса без www отпред.

**Comment by Glamdring** [comment]
Писах в МС, оправиха го :)

**Comment by mitio** [comment]
:clap: :clap: :bow:

Сложих Nginx правило да премахва www-то, ако се заяви така и просто да препраща към варианта без www.
