### ISSUE TITLE
Еднакви CSV файлове за "Резултати по училища от националното външно оценяване за VII клас" и  "Резултати по училища от националното външно оценяване за IV клас"

### ISSUE THREAD

**Issue by glissev** [governmentbg/opendata#23]
Здравейте, 

CSV файловете за "Резултати по училища от националното външно оценяване за VII клас" (https://opendata.government.bg/dataset/rezultati-po-uchilishta-ot-natzionalnoto-vanshno-otzenyavane-za-sedmi-klas) и "Резултати по училища от националното външно оценяване за IV клас" (https://opendata.government.bg/dataset/natzionalno-vanshno-otzenyavane-chetvarti-klas) са с еднакво съдържание. Имената им са различни, но данните в тях са едни и същи.

**Comment by mitio** [comment]
@glissev Благодаря на сигнала! Предадохме на когото трябва, вероятно е неволна техническа грешка. Ще изчакаме да видим какво ще кажат от МОН.

**Comment by mitio** [comment]
@glissev Готово, би трябвало да е коригирано. Файловете са:
- https://opendata.government.bg/dataset/natzionalno-vanshno-otzenyavane-chetvarti-klas/resource/80065510-6737-4e44-bb26-ba0df1d59f4f
- https://opendata.government.bg/dataset/rezuntati7kl/resource/428d3028-5f4d-47ee-8520-0d814074be06

Отново, благодаря за сигнала!

**Comment by glissev** [comment]
И аз благодаря :-).
