### ISSUE TITLE
Редовни backup-и

### ISSUE THREAD

**Issue by antitoxic** [governmentbg/opendata#27]
Автоматични backup-и:
- Веднъж месечно.
- Веднъж всеки ден за последните 10 дни.
- Опционално веднъж всяка седмица за последните 6 седмици.

Трябва да са на физически различен сървър.

**Comment by antitoxic** [comment]
Подали сме параметри за нужния хардуер. Изчакваме достъп.

**Comment by antitoxic** [comment]
ping @Glamdring 
за инфо към @krokodilerian

**Comment by antitoxic** [comment]
ping @Glamdring

**Comment by mitio** [comment]
Това е направено, като за момента за втори сървър, където да се слагат бекъпите, се ползва сървърът на Общество.
