### ISSUE TITLE
Настройване на автоматизирано следене на системните ресурси

### ISSUE THREAD

**Issue by antitoxic** [governmentbg/opendata#32]
Памет, процесорно време, дисково пространство, тн.

Настройване и на автоматизирано следене на достъпността/availability на портала и своевременна реакция при спирането му

**Comment by RadoRado** [comment]
Какви са ограниченията тук откъм използване на 3rd party services за availability?
Предполагам, ще има, защото е държавен проект.

**Comment by antitoxic** [comment]
Това го ще го поемем аз и @krokodilerian за сега. 

3rd party за какво? Лесно е за availability да се ползват, няма и проблем. Другото свързано със самия сървър и това колко е натоварен какво може да се ползва? Най-вероятно inhouse script или?

**Comment by RadoRado** [comment]
За availability по-скоро ме интересуваше :+1: Ние ползваме https://uptimerobot.com/ и работи добре.

А щом ще го поемате с Крокодила - ще следа това issue с интерес ^_^

**Comment by antitoxic** [comment]
Точно същото се ползва и в момента. Uptime downtime съобщения с лопата да ги ринеш. И това ще пробваме да подобрим.

**Comment by krokodilerian** [comment]
Какво има до момента:

https://pnag.ludost.net/cgi-bin/nagios3/status.cgi?host=opendata - nagios с няколко услуги;
https://marla.ludost.net/munin/obshtestvo.bg/opendata.obshtestvo.bg/index.html - munin.
https://ludost.net/cgi-bin/smokeping.cgi?target=Connectivity.opendata - smokeping, за свръзаността

Доколкото знам, има и uptime robot, който праща някаква поща.

**Comment by mitio** [comment]
Настроено е Uptime Robot, както и Nagios + Munin:

- http://pnag.ludost.net/cgi-bin/nagios3/extinfo.cgi?type=1&host=opendata
- https://marla.ludost.net/munin/government.bg/opendata.government.bg/index.html
