### ISSUE TITLE
Информационна секция / CMS

### ISSUE THREAD

**Issue by Glamdring** [governmentbg/opendata#44]
Нужно е място/секция, където да се публикува "информация" (може и под формата на новини, например) - за европейския opendata портал, за решенията на министерски съвет за отваряне на данни, и такива неща. Ако CKAN не го поддържа, може да е нещо външно, Wordpress например, и да има линк към него. 

П.П. това е със сравнително висок приоритет и е добре да се добави както към новата версия, която подготвяте, така и към настоящия портал (за да могат хората от МС да качват информация).

**Comment by RadoRado** [comment]
До колкото разгледах CKAN, няма такава предвидена функционалност.

Какви са изискванията към тези новини?
- Само уеб ли трябва да се чете?
- Email notifications?
- RSS Feed, който да се интегрира някъде?
- Кой ще пише съответните новини?
- Как трябва да изглежда стилово? Като http://opendata.government.bg/ ?

Освен Wordpress, може да се сложи нещо малко по-статично (идващо, със своите ограничения, разбира се).

Вариант е нещо като https://jekyllrb.com/ но там се пише на някакъв markup / markdown.

**Comment by Glamdring** [comment]
- ако "само уеб" включва "мобилен уеб" - да, достатъчно е
- email notifications - желателно
- RSS feed - по-скоро да, или някаква форма на машинна четимост. Ще е иронично новините за отворени данни да не са отворени данни :)
- новините ще ги пишат в дирекция в Министерски съвет
- стилово - близко до портала (същото лого и цветове, т.е.)

Wordpress мисля, че ще е безболезнено. На поддомейн, напр (но на същия сървър).

**Comment by mitio** [comment]
Изисквания към CMS-а (вероятно WordPress) – @Glamdring, допълвай:
- Да изглежда визуално като част от [портала](https://opendata.government.bg/) – да има същия хедър, футър, цветова гама и шрифтове.
- Може да е на поддомейн или subpath (news, cms, pages, blog, ...) Давайте предложения.
- Темата да е responsive и да изглежда окей на тесни екрани (не е нужно да се държи по същия начин както портала, той в момента не е изцяло responsive). Освен това, няма други изисквания, освен да е семпла и изчистена, с фокус върху съдържанието.
- Бонус е да има email notifications за нови публикации.
- Силно желателно е да има RSS feed за нови публикации (форма на машинна четимост е).
- Новините ще ги пишат няколко човека от дирекция в Министерски съвет, те имат нужда от потребители.
- Всичко, което се разработва, трябва да е отворен код. Това включва вероятно темата + някакъв инсталационен скрипт или инструкции за инсталация. Лицензът трябва да е MIT, или, ако не може, GPL. Всички продукти на изработката трябва да се качват в хранилище в тази организация https://github.com/governmentbg/.
- Трябва да се ползва Git.
- Разработката трябва да се случва "на открито", като всички issues и приоритети ще се дискутират в GitHub, в хранилището на проекта.
- Стратегия за прилагане на security updates – ръководство за това как да се прави, ако може да се прави от потребителите или от техническия екип, движещ други разработки по портала, или алтернативно предложение с оферта за security updates.
- Стратегия за създавне на архивни копия на съдържанието – скрипт за Debian-базиран Linux, или ръководство. 

/cc @mihail-ivanov

**Comment by mihail-ivanov** [comment]
Ще разгледам как стоят нещата за WordPress. Един познат ми спомена, че има някакви генератори на теми, с които много лесно можем да направим темата да изглежда като [портала](https://opendata.government.bg/). Ще видя какви са и дали ще ни свършат работа.

**Comment by Glamdring** [comment]
Извинявам се за забавянето. 
- поддомейн - нека е info.opendata.government.bg
- какви бутони да има на портала: "новини и информация" 
- какви секции да има в WP: "Новини", "Ръководства", "Правна рамка", "Списъци с набори от данни за публикуване"

**Comment by mitio** [comment]
**Допълнения**

На база на въпроси, зададени от @vlood, @yanah и други по изискванията по-горе, както и на информация, предоставена от @Glamdring, допълвам следната информация:
- Сайтът ще работи на Debian-базирана OS, като за задвижване ще се ползва Nginx + PHP-FPM. В момента наличната PHP версия на сървъра е 5.4.45, но може да я обновим до PHP 7.
- Трябва да има ограничение на достъпа до административния панел само за определени IP адреси, като това ще се реализира на ниво Nginx конфигурация, както и самите Automattic предлагат [тук](https://codex.wordpress.org/Nginx) и [тук](https://codex.wordpress.org/Brute_Force_Attacks).
- Не е нужно при промяна в хранилището на сайта промените автоматично да ходят към живия сайт, но е добре да има добре документирана и улеснена процедура за deploy на компонените, които са изработени специално за сайта (например темата и плъгини, ако има такива).
- За момента не се изисква поддръжка на многоезичност.
- Посещаемостта на сайта ще се следи с Google Analytics. Няма нужда от друго към момента.
- Няма нужда от специални, допълнителни усилия за SEO, освен това, което е вградено в WordPress и добре структуриран и изчистен семантичен HTML код на темата.
- Няма да има очакване да се "налива" съдържание от изпълнителя.
- Точната структура на категори, страници и подобни не е твърдо фиксирана все още. Изпълнителят може да използва примерната, описана по-горе и да предостави кратко ръководство/напътствия за това как е добре да се структурира съдържание в WP, за да може колегите от Министерски съвет и @Glamdring да направят необходимите категории, тагове, страници и постове сами.

**Въпроси**
- Въпрос към @Glamdring, за по-подробно описание как искаме да работят известията по имейл. **EDIT**: Това @RadoRado го предложи първоначално и си мисля, че ако няма хитър начин да ползваме стандартна WP функционалност за това, ще е добре просто да отпадне, след като има RSS feed.
- Въпрос към всички, който за мен е все още отворен – как ще се подходи с обновяването на промените на сайта. За WordPress и за плъгините често излизат обновления и в самия WP има възможност за обновяване през админа. Как би се вписало това в необходимостта да има хранилище с кода на проекта?
  
  @vlood предлага следното по темата с update:
  
  > "Ще забраним всякаква промяна на PHP файловете в сайта от страна на уеб-сървъра, така че дори някой да стигне до административния панел, да не може да причини съществени щети. Обновяванията могат да се правят на ръка дистанционно на изолирана тестова среда, след което при успех да се push-ват в master, от където да влизат на живия сайт. Обновяването на базата данни обичайно става автоматично и рядко изисква внимание, а когато го изисква, то е чрез привличане на вниманието на администраторите, без да проличава в представителната част на сайта."
  
  На база на написаното от него, ми се струва, че добър вариант за long-term решение би бил:
  - Да се сведат до минимум промените по WP, по възможност само до custom тема, или дори само до custom CSS.
  - В хранилището за проекта да няма код, който е публично достъпен от другаде (код на WordPress и плъгини), а само код на нещата, които са custom разработка (например темата) + ръководства + скрипт(ове) за deploy/update/backup, ако има такива.
  - Да има скрипт или метод по автоматизиран бекъп, която дава възможност и за автоматизиран restore. Това да върви поне веднъж на ден и да може да се пуска ръчно. Не е нужно този скрипт да е част от проекта и ние ще помогнем да се разработи, ако в проекта се опише кое е нужно да се архивира (user uploads, базата, версиите на инсталирания WP и плъгини, друго?) и какво е нужно, за да се възстанови този бекъп (това е почти същото, като да се направи install/deploy, така че тези неща могат да се съчетаят).
  - При нужда от update, първо се пуска бекъп, след това се прави през админа директно на production и ако нещо се омаже – се възстановява бекъпа.

**Comment by vlood** [comment]
Предвид простотата на инсталацията, съвсем спокойно може да се мине без кой знае какви промени в кода. Ако се ползва готова тема, на чиято база се разработва сайта във вид на opendata.government.bg, може да се създаде дъщерна тема, така че дори да не се променя нищо по родителската и да може спокойно да се обновява тя, без да се губят промени.

Вкратце - предложението на @mitio за архивите преди обновяване и възстановяването им при фал е приложима и уместна в случая.

**Comment by Glamdring** [comment]
RSS feed e ok. Пингвайте ме и по други канали, ако се чака нещо от мен, а не съм отговорил :)

**Comment by mitio** [comment]
Тази система вече е публична.
