### ISSUE TITLE
Лиценз по подразбиране

### ISSUE THREAD

**Issue by Glamdring** [governmentbg/opendata#45]
Тъй като в индекса на OKFN основен проблем ни е липсата на лиценз, нека при добавяне на масив да има избран по подразбиране. Напр.някой creative commons.

**Comment by RadoRado** [comment]
Като гледам формата за създаване на dataset, по подразбиране е посочен `CCZero`. Това ли търсим като ефект? Версията е CKAN 2.5.1

![image](https://cloud.githubusercontent.com/assets/387867/14066178/bbfe2508-f44b-11e5-8cdb-f18026488f05.png)

**Comment by Glamdring** [comment]
Да, това :)
