### ISSUE TITLE
Карта ДЗИ 2015

### ISSUE THREAD

**Issue by 11111111110000000000** [governmentbg/opendata#47]
Здравейте, 

Мога ли да ви задам няколко въпроса за картата тук:(http://viz.opendata.government.bg/visuals/edu-map.html) 
1. Има ли тук данни за текущото оценяване по училища или това са само ДЗИ оценки?
2. Защо цифрата в "Общо" на места не съвпада с реалната средноартиметична от всички ДЗИ: Направих около 10 проверки, не излиза същата. Каква е методологията, по която се смята "Общо"?

**Comment by mitio** [comment]
@ppetrovcsr, би ли могъл да погледнеш и отговориш?

Между другото, удачно място за въпроси, свързани с визуализациите, е в [тяхното хранилище](https://github.com/governmentbg/data-viz).

**Comment by pdpetrov** [comment]
Привет,

Скриптът не изчислява "Общо" като средно аритметична или въз основа на друга формула, а единствено представя стойността от официалните данни, [публикувани на портала](https://opendata.government.bg/dataset/rezultati-ot-darjavnite-zrelostni-izpiti-po-uchilishta-i-po-predmeti), в колоната "Общ ср.успех".

В случай, че на визуализацията виждате различна стойност за определено училище от публикуваната на портала, моля напишете и името на училището, за да мога да проверя. Благодаря!

Предполагам, че разминаването между Вашите изчисления и публикуваните стойности се получава, понеже МОН са изчислили стойността "Общ ср. успех" на база реалните оценки на учениците, взети с няколко знака след десетичната запетая и са закръглили до третия при публикуването.

Поздрави

**Comment by 11111111110000000000** [comment]
Здравейте, 

Благодаря за бързия отговор и препоръките. 

Разликата не идва от няколкото знака след десетичната запетая, тъй като при мен разминаването е с 10-20 стотни на места. Много странно.

Не получих отговор на въпорс номер 1? Има ли данни за текущото оценяване в съответните училища (оценяване през годината, срочни оценки) или това тук са оценките само от ДЗИ?

**Comment by pdpetrov** [comment]
Привет,

По отношение на първия въпрос, данните са от _дърваните зрелостни изпити майска сесия 2015_ година. Тази информация е указана и в описанието на визуализацита, и в описанието на данните на портала. Вероятно затова съм пропуснал, да го напиша, извинявам се.

По отношение на разликата, ако правилно разбирам от първия коментар, използвате средно аритметичната от всички ДЗИ, т.е. сумата от средните резултати по предмети разглена на броя предмети. Ако вместо това използвате претеглената средна, като теглото на ДЗИ е според броя ученици, които са положили изпита, би следвало да получите много по-близък резултат до представения (в рамките на стотици). Така например теглото на БЕЛ винаги ще е около 50%, понеже това е задължителният предмет за всеки ученик.

Поздрави

**Comment by 11111111110000000000** [comment]
Много благодаря! 

Поздрави и успех!

**Comment by mitio** [comment]
Считам въпросите за затворени и затвярям и issue-то.
